### ISSUE TITLE
Need of Dimensioning?

### ISSUE THREAD

**Issue by jatin-47** [bhajay/ACADGen#6]
Why there is a need of dimensioning when we can insure that all three views should have same length/pixel as all three views are commonly generated simultaneously. We can just have one scaling factor for all 3 views.

Okay so you have mentioned in the paper that the 3 views can we taken separately as a picture from a photo via a camera so that would need dimensioning but I believe that considering this scenario is useless as then how the user will figure out the right dimensions for a view? By measuring the length of the picture taken!!! (That's bit odd)

**Comment by Abhishek-Rajendra** [comment]
You don't have to measure the length of the object in the picture, You can provide the actual dimensions used for drawing that object.  You can see in the code we actually calculate the length/pixel of the dimension in each view and multiply it with the actual dimension of the object. By doing so we will have the same dimensional unit which we can compare all the views.
